name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - main
    paths:
      - 'worker/**' # Trigger only when changes occur in the 'worker' directory

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or your preferred Node.js version

      - name: Install dependencies for Worker
        run: npm install
        working-directory: ./worker # IMPORTANT: Run npm install in the worker directory

      - name: Deploy Worker
        run: npx wrangler deploy --minify --env production
        working-directory: ./worker # IMPORTANT: Run wrangler deploy in the worker directory
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          WHATSAPP_ACCESS_TOKEN: ${{ secrets.WHATSAPP_ACCESS_TOKEN }}
          WHATSAPP_PHONE_NUMBER_ID: ${{ secrets.WHATSAPP_PHONE_NUMBER_ID }}
          WHATSAPP_API_VERSION: ${{ secrets.WHATSAPP_API_VERSION }}
          NODE_VERSION: 20 # Explicitly set Node.js version for consistency
